import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of alumnos.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Alumnos implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** num_alu. */
	private Integer numAlu;

	/** nombre. */
	private String nombre;

	/** grupo. */
	private String grupo;

	/** The set of cursan. */
	private Set<Cursan> cursanSet;

	/** The set of hacen. */
	private Set<Hacen> hacenSet;

	/** The set of realizan. */
	private Set<Realizan> realizanSet;

	/**
	 * Constructor.
	 */
	public Alumnos() {
		this.cursanSet = new HashSet<Cursan>();
		this.hacenSet = new HashSet<Hacen>();
		this.realizanSet = new HashSet<Realizan>();
	}

	/**
	 * Set the num_alu.
	 * 
	 * @param numAlu
	 *            num_alu
	 */
	public void setNumAlu(Integer numAlu) {
		this.numAlu = numAlu;
	}

	/**
	 * Get the num_alu.
	 * 
	 * @return num_alu
	 */
	public Integer getNumAlu() {
		return this.numAlu;
	}

	/**
	 * Set the nombre.
	 * 
	 * @param nombre
	 *            nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the nombre.
	 * 
	 * @return nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the grupo.
	 * 
	 * @param grupo
	 *            grupo
	 */
	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	/**
	 * Get the grupo.
	 * 
	 * @return grupo
	 */
	public String getGrupo() {
		return this.grupo;
	}

	/**
	 * Set the set of the cursan.
	 * 
	 * @param cursanSet
	 *            The set of cursan
	 */
	public void setCursanSet(Set<Cursan> cursanSet) {
		this.cursanSet = cursanSet;
	}

	/**
	 * Add the cursan.
	 * 
	 * @param cursan
	 *            cursan
	 */
	public void addCursan(Cursan cursan) {
		this.cursanSet.add(cursan);
	}

	/**
	 * Get the set of the cursan.
	 * 
	 * @return The set of cursan
	 */
	public Set<Cursan> getCursanSet() {
		return this.cursanSet;
	}

	/**
	 * Set the set of the hacen.
	 * 
	 * @param hacenSet
	 *            The set of hacen
	 */
	public void setHacenSet(Set<Hacen> hacenSet) {
		this.hacenSet = hacenSet;
	}

	/**
	 * Add the hacen.
	 * 
	 * @param hacen
	 *            hacen
	 */
	public void addHacen(Hacen hacen) {
		this.hacenSet.add(hacen);
	}

	/**
	 * Get the set of the hacen.
	 * 
	 * @return The set of hacen
	 */
	public Set<Hacen> getHacenSet() {
		return this.hacenSet;
	}

	/**
	 * Set the set of the realizan.
	 * 
	 * @param realizanSet
	 *            The set of realizan
	 */
	public void setRealizanSet(Set<Realizan> realizanSet) {
		this.realizanSet = realizanSet;
	}

	/**
	 * Add the realizan.
	 * 
	 * @param realizan
	 *            realizan
	 */
	public void addRealizan(Realizan realizan) {
		this.realizanSet.add(realizan);
	}

	/**
	 * Get the set of the realizan.
	 * 
	 * @return The set of realizan
	 */
	public Set<Realizan> getRealizanSet() {
		return this.realizanSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numAlu == null) ? 0 : numAlu.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Alumnos other = (Alumnos) obj;
		if (numAlu == null) {
			if (other.numAlu != null) {
				return false;
			}
		} else if (!numAlu.equals(other.numAlu)) {
			return false;
		}
		return true;
	}

}
