import java.io.Serializable;
import java.util.Date;

/**
 * Model class of elaboran.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Elaboran implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** practicas. */
	private Practicas practicas;

	/** profesores. */
	private Profesores profesores;

	/** fecha. */
	private Date fecha;

	/**
	 * Constructor.
	 */
	public Elaboran() {
	}

	/**
	 * Set the practicas.
	 * 
	 * @param practicas
	 *            practicas
	 */
	public void setPracticas(Practicas practicas) {
		this.practicas = practicas;
	}

	/**
	 * Get the practicas.
	 * 
	 * @return practicas
	 */
	public Practicas getPracticas() {
		return this.practicas;
	}

	/**
	 * Set the profesores.
	 * 
	 * @param profesores
	 *            profesores
	 */
	public void setProfesores(Profesores profesores) {
		this.profesores = profesores;
	}

	/**
	 * Get the profesores.
	 * 
	 * @return profesores
	 */
	public Profesores getProfesores() {
		return this.profesores;
	}

	/**
	 * Set the fecha.
	 * 
	 * @param fecha
	 *            fecha
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/**
	 * Get the fecha.
	 * 
	 * @return fecha
	 */
	public Date getFecha() {
		return this.fecha;
	}


}
