import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of practicas.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Practicas implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** cod_practica. */
	private Integer codPractica;

	/** titulo. */
	private String titulo;

	/** nivel. */
	private Integer nivel;

	/** The set of elaboran. */
	private Set<Elaboran> elaboranSet;

	/** The set of realizan. */
	private Set<Realizan> realizanSet;

	/**
	 * Constructor.
	 */
	public Practicas() {
		this.elaboranSet = new HashSet<Elaboran>();
		this.realizanSet = new HashSet<Realizan>();
	}

	/**
	 * Set the cod_practica.
	 * 
	 * @param codPractica
	 *            cod_practica
	 */
	public void setCodPractica(Integer codPractica) {
		this.codPractica = codPractica;
	}

	/**
	 * Get the cod_practica.
	 * 
	 * @return cod_practica
	 */
	public Integer getCodPractica() {
		return this.codPractica;
	}

	/**
	 * Set the titulo.
	 * 
	 * @param titulo
	 *            titulo
	 */
	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	/**
	 * Get the titulo.
	 * 
	 * @return titulo
	 */
	public String getTitulo() {
		return this.titulo;
	}

	/**
	 * Set the nivel.
	 * 
	 * @param nivel
	 *            nivel
	 */
	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	/**
	 * Get the nivel.
	 * 
	 * @return nivel
	 */
	public Integer getNivel() {
		return this.nivel;
	}

	/**
	 * Set the set of the elaboran.
	 * 
	 * @param elaboranSet
	 *            The set of elaboran
	 */
	public void setElaboranSet(Set<Elaboran> elaboranSet) {
		this.elaboranSet = elaboranSet;
	}

	/**
	 * Add the elaboran.
	 * 
	 * @param elaboran
	 *            elaboran
	 */
	public void addElaboran(Elaboran elaboran) {
		this.elaboranSet.add(elaboran);
	}

	/**
	 * Get the set of the elaboran.
	 * 
	 * @return The set of elaboran
	 */
	public Set<Elaboran> getElaboranSet() {
		return this.elaboranSet;
	}

	/**
	 * Set the set of the realizan.
	 * 
	 * @param realizanSet
	 *            The set of realizan
	 */
	public void setRealizanSet(Set<Realizan> realizanSet) {
		this.realizanSet = realizanSet;
	}

	/**
	 * Add the realizan.
	 * 
	 * @param realizan
	 *            realizan
	 */
	public void addRealizan(Realizan realizan) {
		this.realizanSet.add(realizan);
	}

	/**
	 * Get the set of the realizan.
	 * 
	 * @return The set of realizan
	 */
	public Set<Realizan> getRealizanSet() {
		return this.realizanSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codPractica == null) ? 0 : codPractica.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Practicas other = (Practicas) obj;
		if (codPractica == null) {
			if (other.codPractica != null) {
				return false;
			}
		} else if (!codPractica.equals(other.codPractica)) {
			return false;
		}
		return true;
	}

}
