import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of asignaturas.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Asignaturas implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** num_asi. */
	private Integer numAsi;

	/** nombre. */
	private String nombre;

	/** profesores. */
	private Profesores profesores;

	/** The set of cursan. */
	private Set<Cursan> cursanSet;

	/**
	 * Constructor.
	 */
	public Asignaturas() {
		this.cursanSet = new HashSet<Cursan>();
	}

	/**
	 * Set the num_asi.
	 * 
	 * @param numAsi
	 *            num_asi
	 */
	public void setNumAsi(Integer numAsi) {
		this.numAsi = numAsi;
	}

	/**
	 * Get the num_asi.
	 * 
	 * @return num_asi
	 */
	public Integer getNumAsi() {
		return this.numAsi;
	}

	/**
	 * Set the nombre.
	 * 
	 * @param nombre
	 *            nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the nombre.
	 * 
	 * @return nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the profesores.
	 * 
	 * @param profesores
	 *            profesores
	 */
	public void setProfesores(Profesores profesores) {
		this.profesores = profesores;
	}

	/**
	 * Get the profesores.
	 * 
	 * @return profesores
	 */
	public Profesores getProfesores() {
		return this.profesores;
	}

	/**
	 * Set the set of the cursan.
	 * 
	 * @param cursanSet
	 *            The set of cursan
	 */
	public void setCursanSet(Set<Cursan> cursanSet) {
		this.cursanSet = cursanSet;
	}

	/**
	 * Add the cursan.
	 * 
	 * @param cursan
	 *            cursan
	 */
	public void addCursan(Cursan cursan) {
		this.cursanSet.add(cursan);
	}

	/**
	 * Get the set of the cursan.
	 * 
	 * @return The set of cursan
	 */
	public Set<Cursan> getCursanSet() {
		return this.cursanSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numAsi == null) ? 0 : numAsi.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Asignaturas other = (Asignaturas) obj;
		if (numAsi == null) {
			if (other.numAsi != null) {
				return false;
			}
		} else if (!numAsi.equals(other.numAsi)) {
			return false;
		}
		return true;
	}

}
