import java.io.Serializable;

/**
 * Model class of cursan.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Cursan implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** alumnos. */
	private Alumnos alumnos;

	/** asignaturas. */
	private Asignaturas asignaturas;

	/** trimestre. */
	private Integer trimestre;

	/**
	 * Constructor.
	 */
	public Cursan() {
	}

	/**
	 * Set the alumnos.
	 * 
	 * @param alumnos
	 *            alumnos
	 */
	public void setAlumnos(Alumnos alumnos) {
		this.alumnos = alumnos;
	}

	/**
	 * Get the alumnos.
	 * 
	 * @return alumnos
	 */
	public Alumnos getAlumnos() {
		return this.alumnos;
	}

	/**
	 * Set the asignaturas.
	 * 
	 * @param asignaturas
	 *            asignaturas
	 */
	public void setAsignaturas(Asignaturas asignaturas) {
		this.asignaturas = asignaturas;
	}

	/**
	 * Get the asignaturas.
	 * 
	 * @return asignaturas
	 */
	public Asignaturas getAsignaturas() {
		return this.asignaturas;
	}

	/**
	 * Set the trimestre.
	 * 
	 * @param trimestre
	 *            trimestre
	 */
	public void setTrimestre(Integer trimestre) {
		this.trimestre = trimestre;
	}

	/**
	 * Get the trimestre.
	 * 
	 * @return trimestre
	 */
	public Integer getTrimestre() {
		return this.trimestre;
	}


}
