import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of profesores.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Profesores implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** num_prof. */
	private Integer numProf;

	/** nombre. */
	private String nombre;

	/** The set of asignaturas. */
	private Set<Asignaturas> asignaturasSet;

	/** The set of elaboran. */
	private Set<Elaboran> elaboranSet;

	/**
	 * Constructor.
	 */
	public Profesores() {
		this.asignaturasSet = new HashSet<Asignaturas>();
		this.elaboranSet = new HashSet<Elaboran>();
	}

	/**
	 * Set the num_prof.
	 * 
	 * @param numProf
	 *            num_prof
	 */
	public void setNumProf(Integer numProf) {
		this.numProf = numProf;
	}

	/**
	 * Get the num_prof.
	 * 
	 * @return num_prof
	 */
	public Integer getNumProf() {
		return this.numProf;
	}

	/**
	 * Set the nombre.
	 * 
	 * @param nombre
	 *            nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the nombre.
	 * 
	 * @return nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the set of the asignaturas.
	 * 
	 * @param asignaturasSet
	 *            The set of asignaturas
	 */
	public void setAsignaturasSet(Set<Asignaturas> asignaturasSet) {
		this.asignaturasSet = asignaturasSet;
	}

	/**
	 * Add the asignaturas.
	 * 
	 * @param asignaturas
	 *            asignaturas
	 */
	public void addAsignaturas(Asignaturas asignaturas) {
		this.asignaturasSet.add(asignaturas);
	}

	/**
	 * Get the set of the asignaturas.
	 * 
	 * @return The set of asignaturas
	 */
	public Set<Asignaturas> getAsignaturasSet() {
		return this.asignaturasSet;
	}

	/**
	 * Set the set of the elaboran.
	 * 
	 * @param elaboranSet
	 *            The set of elaboran
	 */
	public void setElaboranSet(Set<Elaboran> elaboranSet) {
		this.elaboranSet = elaboranSet;
	}

	/**
	 * Add the elaboran.
	 * 
	 * @param elaboran
	 *            elaboran
	 */
	public void addElaboran(Elaboran elaboran) {
		this.elaboranSet.add(elaboran);
	}

	/**
	 * Get the set of the elaboran.
	 * 
	 * @return The set of elaboran
	 */
	public Set<Elaboran> getElaboranSet() {
		return this.elaboranSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numProf == null) ? 0 : numProf.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Profesores other = (Profesores) obj;
		if (numProf == null) {
			if (other.numProf != null) {
				return false;
			}
		} else if (!numProf.equals(other.numProf)) {
			return false;
		}
		return true;
	}

}
